Migrate to tools.dep (#36)
* Migrate to tools.dep

* Cleanup developer guide

* Remove code to get driver version

This will be fixed in https://github.com/exasol/metabase-driver/issues/40

* Install driver for running integration tests

This avoids error

java.lang.IllegalArgumentException: No method in multimethod 'connection-properties' for dispatch value: :exasol

* Build frontend to fix failing integration tests

 ERROR in metabase.pulse.render.js-svg-test/combo-test (js_engine.clj:38)
[PRO TIP] If this test fails, you may need to rebuild the bundle with `yarn build-static-viz`

Uncaught exception, not in assertion.

clojure.lang.ExceptionInfo: Javascript resource not found: frontend_client/app/dist/lib-static-viz.bundle.js
    source: "frontend_client/app/dist/lib-static-viz.bundle.js"

* Upgrade to Metabase 0.43.1

* Remove features not supported in the latest release of metabase

* Activate linting with clj kondo