#1-project-setup (#2)
* Initial project setup

* Add basic implementation

* Fix conversion of data types

* Build driver uberjar

* Download metabase jar as dependency

* Add ci build

* Install clojure

* Add user guide

* Add troubleshooting guide

* Add dependency for JDBC driver

* Code cleanup

* Improve documentation, add initial unit test

* Add broken links checker

* Add linter

* Replace action with apt install

* Disable link checker for local url

* Fix printing Clojure version

* Use clj-kondo instead of eastwood for linting

* Add file to avoid failing linter

 WARNING: user-level profile defined in project files.
test:0:0: error: file does not exist
linting took 16ms, errors: 1, warnings: 0
Error: Process completed with exit code 3.

* Enable caching for clj-kondo linter

% time lein lint
WARNING: user-level profile defined in project files.
linting took 82ms, errors: 0, warnings: 0
lein lint  66.53s user 1.75s system 126% cpu 54.136 total
% time lein lint
WARNING: user-level profile defined in project files.
[clj-kondo] nrepl-0.8.3.jar was already linted, skipping
[clj-kondo] incomplete-0.1.0.jar was already linted, skipping
[clj-kondo] clojure-1.10.0.jar was already linted, skipping
[clj-kondo] spec.alpha-0.2.176.jar was already linted, skipping
[clj-kondo] core.specs.alpha-0.2.44.jar was already linted, skipping
[clj-kondo] metabase-0.41.2.jar was already linted, skipping
linting took 40ms, errors: 0, warnings: 0
lein lint  8.57s user 0.57s system 113% cpu 8.042 total

* Implement review findings by @jakobbraun

* Update doc/user_guide/user_guide.md

Co-authored-by: jakobbraun <jakob.braun@posteo.de>

Co-authored-by: jakobbraun <jakob.braun@posteo.de>